spring:
  application:
    name: celk-auth-engine
  datasource:
    url: jdbc:mysql://localhost:3306/celk?createDatabaseIfNotExist=true&useSSL=false&verifyServerCertificate?=false
    username: celk
    password: celk
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    properties.hibernate.format_sql: false
  redis:
    host: localhost
    password:
    port: 6379