version: '3'
services:
  celk-mysql:
    container_name: celk-mysql
    restart: always
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=celk
      - MYSQL_DATABASE=celk
      - MYSQL_USER=celk
      - MYSQL_PASSWORD=celk
  celk-redis:
    container_name: celk-redis
    image: 'redis:6.0-rc1'
    ports:
      - '6379:6379'
  celk-auth-engine:
    container_name: celk-auth-engine
    image: caibate/celk-auth-engine:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://celk-mysql:3306/celk?createDatabaseIfNotExist=true&useSSL=false&verifyServerCertificate?=false&allowPublicKeyRetrieval=true
      - SPRING_REDIS_HOST=celk-redis
    ports:
      - "8080:8080"
    depends_on:
      - celk-mysql
      - celk-redis

## Build image
#docker build -t <image_name> .```
## Run image
#`docker run -d -p 3306:3306 <image_name>```